-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Tempo de geração: 23/12/2021 às 13:44
-- Versão do servidor: 10.3.28-MariaDB-cll-lve
-- Versão do PHP: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `topzjuxz_highshoes`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `cadastro`
--

CREATE TABLE `cadastro` (
  `id` int(11) NOT NULL,
  `username` varchar(30) NOT NULL,
  `nome` varchar(50) DEFAULT NULL,
  `sobrenome` varchar(100) DEFAULT NULL,
  `data_nascimento` date DEFAULT NULL,
  `numero_telefone` bigint(12) NOT NULL,
  `rua` varchar(100) DEFAULT NULL,
  `numero_casa` int(5) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `senha` varchar(20) NOT NULL,
  `photo` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Despejando dados para a tabela `cadastro`
--

INSERT INTO `cadastro` (`id`, `username`, `nome`, `sobrenome`, `data_nascimento`, `numero_telefone`, `rua`, `numero_casa`, `email`, `senha`, `photo`) VALUES
(1, 'murilosinner', 'Murilo', 'SimÃµes', '2004-12-21', 11942986698, 'Pedro Rodrigues Pereira', 310, 'murilorsimoes@gmail.com', '212121', 'DyHMBfB6_400x400.jpg'),
(2, 'admin', 'admin', 'adminnn', '2013-06-18', 11735896898, '', NULL, 'admin@demo.com.br', 'admin', 'ConverseGiannoGolfLeFleurLavender1.jpg'),
(3, 'Sulivan', '', '', '2021-12-12', 171818718, '', NULL, 'sulivan@gmail.com', '123456', '1648212175'),
(4, 'Ronaldo', '', '', '0000-00-00', 11942986698, '', NULL, 'murilobolinha2112@gmail.com', '123456', ''),
(11, 'dcpowerultra', 'carlos', 'panzariello', '2000-03-16', 24992171797, '', NULL, 'carlosdanielpanzariello@gmail.com', '151621', 'image (1).jpeg'),
(13, 'Bruna', 'Bruna', 'KInjo', '5552-06-23', 9147821455, '', NULL, 'bruna.luiz22@gmail.com', '123456', 'barbie.jpg'),
(16, 'Olivia', 'Olivia', 'Gamer', '1998-05-15', 11786555555, NULL, NULL, 'oliviagamer@gmail.com', '', NULL),
(17, 'Luiza', NULL, NULL, NULL, 11992369637, NULL, NULL, 'lu.henrique.souza22@gmail.com', 'lu289289', NULL),
(18, 'Gabs', 'Gabriel', 'Gomes', '2004-09-21', 11967719745, 'Sua mae', 69, 'gabriel1406.fn@gmail.com', 'gabriel21092004', 'download.png');

-- --------------------------------------------------------

--
-- Estrutura para tabela `produtos`
--

CREATE TABLE `produtos` (
  `id` int(11) NOT NULL,
  `marca` varchar(20) NOT NULL,
  `name` varchar(200) NOT NULL,
  `desc` text NOT NULL,
  `price` float(7,2) NOT NULL,
  `rrp` decimal(7,2) NOT NULL DEFAULT 0.00,
  `quantity` int(11) NOT NULL,
  `img` text NOT NULL,
  `date_added` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Despejando dados para a tabela `produtos`
--

INSERT INTO `produtos` (`id`, `marca`, `name`, `desc`, `price`, `rrp`, `quantity`, `img`, `date_added`) VALUES
(1, 'Adidas', 'TÊNIS 4DFWD TOKYO', 'O tênis segue a linha de inovação do adidas 4D, adicionando ângulos à equação.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Fecho de laço<br>\r\n\r\n- Cabedal adidas Primeknit<br>\r\n\r\n- Sensação de amortecimento<br>\r\n\r\n- Forro têxtil<br>\r\n\r\n- Entressola adidas 4D<br>\r\n\r\n- Solado de borracha<br>', 1299.00, '0.00', 10, 'TÊNIS4DFWDTOKYO1.jpg', '2021-10-23 18:17:22'),
(2, 'Adidas', 'Tênis Yeezy Boost 350 V2 MX Oat', 'O adidas Yeezy Boost 350 V2 “Mx Oat” é um dos lançamentos mais recentes a apresentar o novo padrão “MX”.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Parte superior em tecido Primeknit amarelo coberta em um padrão espiral de tons laranja, azul e dourado<br>\r\n\r\n- Este tênis Lembra um pouco as inversões de cores dos sensores de calor<br>\r\n\r\n- Incluem uma faixa translúcida nas laterais do tênis junto com uma ”pull tab” aba de puxar no calcanhar<br>\r\n<br>\r\n- Forro têxtil<br>\r\n\r\n- Entressola adidas 4D<br>\r\n\r\n- Uma sola translúcida com amortecimento Boost completa o design<br>', 1899.00, '0.00', 10, 'TênisYeezyBoost350V2Mxoat.jpg', '2021-10-23 18:17:22'),
(3, 'Adidas', 'Tênis Yeezy Boost 700 MNVN Bright Cyan', 'Sobre o tênis:<br>\r\n\r\n- Usa uma parte superior leve de poliéster, presa com cordões elásticos sem amarração e com acabamento em um vibrante tom aqua<br>\r\n\r\n- Sobreposições sem costura fornecem durabilidade e suporte leves, enquanto detalhes reflexivos oferecem maior visibilidade em condições de pouca luz.\r\n\r\n- A marca \'700\' da marca do tênis adorna a lateral<br>\r\n\r\n- O amortecimento responsivo chega através da entressola esculpida em PU, com amortecimento Boost de comprimento total e reforçado com uma sola de piso em espinha', 2199.00, '0.00', 10, 'YeezyBoost700MnvnBrightCyan.png', '2021-10-23 18:17:22'),
(4, 'Adidas', 'Bota Yeezy Desert Boot Rock marrom adidas', 'Sobre o tênis:<br>\r\n\r\n- Com cano curto, tela na parte superior<br>\r\n\r\n- Fechamento por cadarço na frente<br>\r\n\r\n- Recortes em camurça e solado em borracha<br>', 3238.00, '0.00', 10, 'BotaYeezyDesertBootRock1.jpg', '2021-10-23 18:17:22'),
(5, 'Adidas', 'TÊNIS ZX 8000 SUPEREARTH', 'A Adidas relança a coleção A-ZX, originalmente concebida em 2008. E, com ela, 26 modelos que homenageiam o legado da lendária saga ZX. A série inclui o novo ZX 8000 \"SuperEarth\".<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Parte superior em tecido<br>\r\n\r\n- Forro em tecido<br>\r\n\r\n- Sola de borracha<br>\r\n\r\n- Tornozelo acolchoado<br>', 899.00, '0.00', 10, 'AdidasZx8000Superearth2.jpg', '2021-10-23 18:17:22'),
(6, 'Adidas', 'TÊNIS ADIDAS YEEZY 500 BRANCO', 'Sobre o tênis:<br>\r\n\r\n- O design do YEEZY é composto por materiais bonitos, mas simples, de cores sóbrias, que dão ao tênis um ar elegante e refinado e atemporal<br>\r\n\r\n- Tudo isso traduz a busca de Kanye West por um estilo effortless. Juntando materiais e tecnologias de ponta da adidas, o YEEZY BOOST 500 é um passo destemido para o futuro da moda urbana<br>', 999.00, '0.00', 10, 'AdidasYeezy500Branco1.jpg', '2021-10-23 18:17:22'),
(7, 'Adidas', 'Tênis Yeezy Boost 350 V2 Mono Ice', 'Sobre o tênis:<br>\r\n\r\n- Bico arredondado, fechamento frontal por amarração, detalhe de tira posterior, logo na palmilha e solado de borracha<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Forro: Poliamida 100%<br>\r\n\r\n- Exterior: Poliéster 100%<br>', 3953.00, '0.00', 10, 'TênisYeezyBoost350V2MonoIce1.jpg', '2021-10-23 18:17:22'),
(8, 'Adidas', 'Tênis Yeezy Boost 350 V2 Butter', 'Sobre o tênis:<br>\r\n\r\n- Com bico arredondado, fechamento por cadarço na frente, primeknit na parte superior, solado com logo, tira na parte posterior e solado em borracha<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Exterior: Poliéster 100%<br>\r\n\r\n- Forro: Poliéster 100%<br>', 5314.00, '0.00', 10, 'AdidasYeezyBoost350V2Butter1.jpg', '2021-10-23 18:17:22'),
(9, 'Adidas', 'Tênis Yeezy 700 V3 Alvah', 'Sobre o tênis:<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Exterior: Nylon 100%, Poliéster 100%, Elastano 100%, Borracha 100%<br>\r\n\r\n- Forro: Poliéster 100%<br>', 6000.00, '0.00', 10, 'TênisYeezy700V3Alvah1.png', '2021-10-23 18:17:22'),
(10, 'Adidas', 'Tênis Yeezy Boost 350 V2 Blue Tint', 'Sobre o tênis:<br>\r\n\r\n- Com tecido em tricô, padronagem colorida, tira na parte posterior, solado flat, bico arredondado e fechamento por cadarço na frente<br>\r\n\r\n- Exterior: Algodão 100%<br>\r\n\r\n- Solado: Borracha 100%<br>', 6854.00, '0.00', 10, 'YeezyBoost350V2BlueTint1.png', '2021-10-23 18:17:22'),
(11, 'Adidas', 'Tênis Yeezy Boost 350 V2 Green', 'Sobre o tênis:<br>\r\n\r\n- Tênis Yeezy Boost 350 V2 \"Green\" preto e verde de algodão, adidas. Com fechamento por cadarço na frente, bico arredondado e em tricô<br>\r\n\r\n- Forro: Algodão 100%<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Exterior: Algodão 100%<br>', 10044.00, '0.00', 10, 'YeezyBoost350V2Green1.jpg', '2021-10-23 18:17:22'),
(12, 'Adidas', 'Tênis Yeezy Boost 750 Grey Gum', 'Sobre o tênis:<br>\r\n\r\n- Cinza de camurça, Yeezy. Com bico arredondado, fechamento por cadarço na frente, solado com logo, fechamento por zíper lateral oculto, recorte acolchoado na abertura e solado em borracha.<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Forro: Poliamida 100%, Couro 100%<br>\r\n\r\n- Exterior: Camurça 100%<br>', 18986.00, '0.00', 10, 'YeezyBoost750GreyGum1.jpg', '2021-10-23 18:17:22'),
(13, 'Adidas', 'Tênis Yeezy Boost 700 Magnet', 'Sobre o tênis:<br>\r\n\r\n- Cinza de camurça, adidas YEEZY. Com bico arredondado e fechamento por cadarço na frente<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Exterior: Camurça 100%, Nylon 100%<br>\r\n\r\n- Forro: Poliéster 100%<br>', 7965.00, '0.00', 10, 'YeezyBoost700Magnet1.jpg', '2021-10-23 18:17:22'),
(14, 'Adidas', 'Tênis Yeezy Boost 700 Sun', 'Sobre o tênis:<br>\r\n\r\n- Bico arredondado, solado tratorado de borracha, detalhe de recorte contrastante, logo na palmilha, fechamento frontal por amarração, recorte de tela e signature cushioned Boost midsole<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Exterior: Camurça 100%, Poliamida 100%<br>\r\n\r\n- Forro: Poliamida 100%<br>', 8088.00, '0.00', 10, 'YeezyBoost700Sun1.jpg', '2021-10-23 18:17:22'),
(15, 'Adidas', 'Tênis YZY QNTM Yeezy Quantum', 'Sobre o tênis:<br>\r\n\r\n- Com bico arredondado, solado em borracha, fechamento por laço, solado com logo e cano alto<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Exterior: Couro 100%, Camurça 100%, Neoprene 100%, Nylon 100%, Poliéster 100%, Elastano 100%<br>\r\n\r\n- Forro: Poliéster 100%<br>', 2273.00, '0.00', 10, 'YZYQNTMYeezyQuantum1.jpeg', '2021-10-23 18:17:22'),
(16, 'Adidas', 'TÊNIS ADIDAS ULTRABOOST X LEGO® COLORS', 'Sobre o tênis:<br>\r\n\r\n- Este tênis de corrida adidas criado com o LEGO Group tem tudo a ver com diversão. Diversão e também conforto. Porque nada precisa atrapalhar o que é bom.<br>\r\n\r\n- Ajuste similar ao de uma meia<br>\r\n\r\n- Fecho de cadarço<br>\r\n\r\n- Cabedal têxtil adidas Primeknit<br>\r\n\r\n- Entressola Boost<br>\r\n\r\n- Forro têxtil<br>\r\n', 899.00, '0.00', 10, 'AdidasUltraboostxLegoColors1.jpg', '2021-10-23 18:17:22'),
(17, 'Adidas', 'Tênis Yeezy Boost 700 V3 Azael', 'Sobre o tênis:<br>\r\n\r\n- Nude e preto de borracha, adidas. Com bico arredondado, solado em borracha, fechamento por cadarço e solado com logo.<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Exterior: Nylon 100%, Poliamida 100%, Elastano 100%, Borracha 100%<br>\r\n\r\n- Forro: Poliéster 100%<br>', 11030.00, '0.00', 10, 'YeezyBoost700V3Azael1.jpg', '2021-10-23 18:17:22'),
(18, 'Adidas', 'Tênis Yeezy Boost 350 V2 Yecheil', 'Sobre o tênis:<br>\r\n\r\n- Com bico arredondado, solado em borracha, fechamento por cadarço e solado com logo<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Exterior: Nylon 100%, Poliéster 100%, Elastano 100%<br>\r\n\r\n- Forro: Poliéster 100%<br>', 5080.00, '0.00', 10, 'YeezyBoost350V2Yecheil1.jpg', '2021-10-23 18:17:22'),
(19, 'Adidas', 'Tênis Yeezy Boost 700 V2 Tephra', 'Sobre o tênis:<br>\r\n\r\n- Com bico arredondado, fechamento por cadarço na frente, detalhe de recortes e solado em borracha<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Exterior: Camurça 100%, Poliéster 100%<br>\r\n\r\n- Forro: Poliéster 100%<br>', 5438.00, '0.00', 10, 'YeezyBoost700V2Tephra1.jpg', '2021-10-23 18:17:22'),
(20, 'Adidas', 'Tênis adidas Yeezy Foam RNNR', 'Sobre o tênis:<br>\r\n\r\n- Bico amendoado e modelagem slip-on<br>\r\n\r\n- Cor: Branco<br>\r\n\r\n- Ao comprar este item unissex, considere que sua grade de tamanhos é masculina<br>\r\n\r\n- Este item é fornecido por um marketplace premium de tênis que reúne peças raras e já esgotadas<br>\r\n\r\n- Solado: Borracha 100%<br>', 12016.00, '0.00', 10, 'AdidasYeezyFoamRNNR1.jpg', '2021-10-23 18:17:22'),
(21, 'Adidas', 'Tênis adidas Ultraboost 5.0 DNA', 'Sobre o tênis:<br>\r\n\r\n- O cabedal tonal destaca sutilmente o tecido da malha, uma combinação de todas as iterações que vieram antes dela<br>\r\n\r\n- Ajuste similar ao de uma meia<br>\r\n\r\n- Fecho de cadarço<br>\r\n\r\n- Cabedal têxtil adidas Primeknit<br>\r\n\r\n- Entressola Boost<br>\r\n\r\n- Forro têxtil<br>', 899.00, '0.00', 10, 'AdidasUltraboost5.0DNA1.jpg', '2021-10-23 18:17:22'),
(22, 'Adidas', 'Tênis Yeezy Boost 350 V2 Beluga', 'Sobre o tênis:<br>\r\n\r\n- Cinza de algodão<br>\r\n\r\n- Com primeknit na parte superior, bico arredondado, fechamento por cadarço na frente e solado em borracha<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Exterior: Microfibra 100%<br>', 11942.00, '0.00', 10, 'YeezyBoost350V2Beluga1.jpg', '2021-10-23 18:17:22'),
(23, 'Adidas', 'Tênis Human Race NMD Breathe Walk', 'Sobre o tênis:<br>\r\n\r\n-Possui estilo slip-on, detalhe de recortes e solado em borracha<br>\r\n\r\n- Exterior: Nylon 100%<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Forro: Nylon 100%<br>', 9015.00, '0.00', 10, 'HumanRaceNMDBreatheWalk1.jpg', '2021-10-23 18:17:22'),
(24, 'Adidas', 'Tênis Human Race NMD Cloud Mood', 'Sobre o tênis:<br>\r\n\r\n- Possui estilo slip-on e solado em borracha<br>\r\n\r\n- Este modelo é originário de um marketplace de tênis premium, cujo estoque traz os tênis de edição limitada mais desejados do momento<br>\r\n\r\n- Exterior: Nylon 100%<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Forro: Nylon 100%<br>', 6379.00, '0.00', 10, 'HumanRaceNMDCloudMood1.jpg', '2021-10-23 18:17:22'),
(25, 'Nike', 'Nike SB Dunk Low Club 58 Gulf', 'Em 2018 a divisão de skateboard da Nike preparou uma nova colorway do Blazer Mid com o nome de “Club 58” inspirada nos carros de corrida da Gulf Racing dos anos 60, nos quais os veículos tinham como principais características o azul e o laranja.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Cabedal: camurça azul-claro<br>\r\n\r\n- Swooshe: couro<br>\r\n\r\n- Insígnia “58” bordada na lateral traseira nas cores branco e preto<br>\r\n\r\n- Sola laranja<br>', 2445.00, '0.00', 10, 'NikeSBDunkLowClub58Gulf1.jpg', '2021-10-23 18:17:22'),
(26, 'Nike', 'SB Dunk Low StrangeLove', 'A StrangeLove Skateboards criou a sua própria estética única ao combinar sua marca e personalidade ao estilo apreciado Dunk Low.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Design revestido de veludo com sobreposições de camurça<br>\r\n\r\n- Tons pastéis<br>\r\n\r\n- Ilustrações de caveiras bordadas em cada calcanhar, marca registrada da StrangeLove<br>\r\n\r\n- Na sola corações discretos<br>', 899.00, '0.00', 10, 'SbDunkLowStrangelove1.png', '2021-10-23 18:17:22'),
(27, 'Nike', 'NIKE X TRAVIS SCOTT SB DUNK LOW \"CACTUS JACK\"', 'O Travis Scott Nike SB Dunk Low Cactus Jack foi a primeira colaboração do artista com a divisão de skate da Nike.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Cabedal: padrão bandana<br>\r\n\r\n- Upper: num tom castanho claro, com overlays em azul-navy<br>\r\n\r\n- Swoosh interior tem um contraste em tons de rosa<br>', 11000.00, '0.00', 10, 'NIKEXTRAVISSCOTTSBDUNKLOWCACTUSJACK1.jpg', '2021-10-23 18:17:22'),
(28, 'Nike', 'Nike Dunk Low SP - Syracuse', 'O Dunk Low Retro SP \'Syracuse\' comemora o 35º aniversário da silhueta com uma colorway clássica da série \'Be True to Your School\' da Nike de 1985.<br> Originalmente representava o time de basquete da Universidade de Syracuse, é reinterpretado como um low-top.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Parte superior em couro<br>\r\n\r\n- Base branca com sobreposições Orange Blaze<br>\r\n\r\n- Etiqueta Nike na língua de malha respirável<br>', 4070.00, '0.00', 10, 'NikeDunkLowSPSyracuse1.jpg', '2021-10-23 18:17:22'),
(29, 'Nike', 'BEN & JERRYS NIKE SB DUNK LOW', 'A Ben & Jerrys, empresa conhecida mundialmente fundada em 1978 foi homenageada pela Nike SB, que produziu uma versão do Dunk Low com tons que imitam a embalagem do pote de Ben & Jerry.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- É composto por um céu azul nublado<br>\r\n\r\n- Parte superior de couro de prado verde com couro falso nas sobreposições e línguas<br>\r\n\r\n- Swooshes amarelos na lateral imita sorvete derretido<br>\r\n\r\n- Interiores tie-dye<br>\r\n\r\n- Sola branca e verde<br>', 10000.00, '0.00', 10, 'NIKESBBEN_JERRYS.png', '2021-10-23 18:17:22'),
(30, 'Nike', 'Nike SB Dunk Low Court Purple', 'O Dunk marcou as quadras como um tênis de basquete, mas seu estilo conquistou também os skatistas por sua durabilidade e resposta rápida sobre o skate. Então em 2002, o modelo foi adaptado para atender melhor às necessidades desse novo público.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Amortecimento Zoom Air no calcanhar<br>\r\n\r\n- Língua acolchoada para mais conforto<br>\r\n\r\n- Design em roxo com tons contrastantes de branco e preto<br>\r\n- Swooshes amarelos na lateral imita sorvete derretido<br>\r\n\r\n- Interiores tie-dye<br>\r\n\r\n- Sola branca e verde<br>', 2760.00, '0.00', 10, 'NikeSbDunkLowCourtPurple1.jpg', '2021-10-23 18:17:22'),
(31, 'Nike', 'Nike Dunk Low University Red 2021', 'Criado para as quadras, mas trazido para as ruas, o Tênis Nike Dunk Low \"University Red\" volta com sobreposições encantadoras e as cores universitárias originais.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- O couro premium na parte de cima<br>\r\n\r\n- Gola acolchoada<br>\r\n\r\n- Cores de times universitários<br>\r\n\r\n- Sola de borracha<br>', 4000.00, '0.00', 10, 'NikeDunkLowUniversityRed2021.jpg', '2021-10-23 18:17:22'),
(32, 'Nike', 'Nike SB Dunk Low Grateful Dead Bears Orange', 'A banda The Grateful Dead é associada a duas ilustrações: o crânio escrito “We Are Everywhere” e os ursos coloridos dançando. Esta edição do Dunk Low usa o ícone dos ursos como inspiração principal.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Detalhes em pele artificial felpuda<br>\r\n\r\n- Sobreposições de camurça na maior parte do cabedal<br>\r\n\r\n- Um Swoosh imita os colares usados pelos ursos<br>', 12000.00, '0.00', 10, 'NikeSBDunkLowGratefulDeadBearsOrange1.jpg', '2021-10-23 18:17:22'),
(33, 'Nike', 'NIKE - Dunk Low SP \"City Market\"', 'O \"City Market\" homenageia os mercados de rua e as embalagens industriais usadas para enviar seus produtos, incluindo sacos de arroz e café que são normalmente reciclados.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Etiqueta similar a um rótulo nutricional enfeita a língua<br>\r\n\r\n- Swoosh transparente<br>\r\n\r\n- Gráfico na palmilha esquerda que diz \"Obrigado por se importar!\"<br>', 3000.00, '0.00', 10, 'Nike-DunkLowSpCityMarket1.jpg', '2021-10-23 18:17:22'),
(34, 'Nike', 'TÊNIS NIKE DUNK LOW PREMIUM \"MEDIUM CURRY\"', 'O Nike Dunk Low Premium ‘Medium Curry’ tem uma silhueta retrô em um cabedal de camurça com tons outonais quentes. Uma base em tom creme é com contraste por sobreposições de curry marrom no dedo do pé e no calcanhar.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Cabedal de camurça<br>\r\n\r\n- Zoom Air<br>\r\n\r\n- Amortecimento Sola de borracha de goma<br>', 899.00, '0.00', 10, 'NikeDunkLowPremiumMediumCurry1.jpg', '2021-10-23 18:17:22'),
(35, 'Nike', 'NIKE x OFF-WHITE - Dunk Low \"Pine Green\"', 'Virgil Abloh busca a arte da desconstrução e recreação com uma coleção cápsula de três peças do OFF-WHITE x Nike Dunk Low.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Parte superior de couro verde e branco<br>\r\n\r\n- Swoosh verde com um detalhe laranja na lateral<br>\r\n\r\n- Cadarço Flywire laranja assinando a estética de Virgil Abloh por cima de todo o cabedal<br>\r\n\r\n- Clássico solado de borracha branco e verde<br>', 5500.00, '0.00', 10, 'NikexOff-white-DunkLowPineGreen1.jpg', '2021-10-23 18:17:22'),
(36, 'Nike', 'Off-White x Nike Dunk University Red', 'A Off-white e a Nike trabalharam juntas novamente e trouxeram uma nova reedição do modelo Nike Dunk Low. A novidade foi vista pela primeira vez na Paris Fashion Week.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Base de couro branco e de couro vermelho<br>\r\n\r\n- Tradicional marca Off-White na etiqueta laranja<br>\r\n\r\n- Sola com contraste por uma sola intermédia branca e uma sola vermelha<br>', 4700.00, '0.00', 10, 'Off-whitexNikeDunkUniversityRed1.png', '2021-10-23 18:17:22'),
(37, 'Nike', 'Off-White Dunk Low University Gold', 'Virgil Abloh busca a arte da desconstrução e recreação com uma coleção cápsula de três peças do OFF-WHITE x Nike Dunk Low.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Bico arredondado<br>\r\n\r\n- Solado flat em borracha<br>\r\n\r\n- Solado com logo e tag com o logo<br>\r\n\r\n- Exterior: Couro 100%<br>', 5260.00, '0.00', 10, 'Off-whiteDunkLowUniversityGold1.jpg', '2021-10-23 18:17:22'),
(38, 'Nike', 'Air Jordan 1 Retro Hight \"Travis Scott”', 'Uma colaboração entre a marca Travis Scott e a Jordan, o \'Mocha\' retrô Travis Scott x Air Jordan 1 Retro High apresenta um Swoosh de tamanho grande no lado lateral. A construção de couro branco caído e camurça Dark Mocha é acentuada pelas marcas University Red Cactus Jack e Nike na língua, enquanto o calcanhar ostenta o logotipo do rosto de Scott de uma maneira gravada.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Colorway: sail/dark mocha-university red-black<br>\r\n\r\n- Data de Lançamento: 11/05/19<br>\r\n\r\n- Logo \"Cactus Jack\" na língua<br>\r\n\r\n- Swoosh preto invertido caindo na sola<br>', 9980.00, '0.00', 10, 'AirJordan1RetroHightTravisScott1.jpg', '2021-10-23 18:17:22'),
(39, 'Nike', 'AIR JORDAN 6 RETRO X TRAVIS SCOTT BRITISH KHAKI ', 'Seguindo os passos do cobiçado \'Olive\' colorway de 2019, o Travis Scott x Air Jordan 6 Retro \'British Khaki\' reúne Jordan Brand com o rapper de Houston.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Parte superior é trabalhada com camurça e tela, acentuada com detalhes Bright Crimson<br>\r\n\r\n- A bolsa stash repete a aparência no colarinho lateral, enquanto novos detalhes com zíper são adicionados ao lado medial<br>\r\n\r\n- Com gráficos adicionais na sola intermédia, sola exterior, lingueta e cadeado<br>', 1499.00, '0.00', 10, 'AirJordan6RetroxTravisScottBritishKhaki1.png', '2021-10-23 18:17:22'),
(40, 'Nike', 'Air Jordan 6 Travis Scoot Medium Olive', 'Em sua colaboração com Jordan Brand, o rager preeminente da música se inspira no Air Jordan VI para um visual que brilha mais quando está escuro.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- A silhueta colaborativa apresenta uma parte superior verde escura em camurça combinada com detalhes em laranja por toda parte<br>\r\n\r\n- Possui um bolso lateral na gola, três opções de cores extra de cadarços, midsole Sail<br>\r\n\r\n- Sola que brilha no escuro<br>\r\n\r\n- Detalhes refletivos da 3M no painel lateral e as marcas Nike Air e Cactus Jack presentes no heel (painel do calcanhar)<br>', 3929.00, '0.00', 10, 'AirJordan6TravisScootMediumOlive1.png', '2021-10-23 18:17:22'),
(41, 'Nike', 'Tênis Nike Air Jordan 1 Retro High Dior - Christian Dior', 'a edição limitada Air Jordan 1 High OG destaca o apelo atemporal do tênis e o estilo da Maison Dior. Projetado usando os mesmos princípios de uma bolsa de luxo, o objetivo de Kim Jones era tornar “o Air Jordan 1 mais luxuoso de todos os tempos”, fabricado inteiramente na Itália, com uma mistura de couro branco e cinza Dior, com um Swoosh Oblique com monograma e bordas pintadas à mão.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Cano alto com AIR DIOR na lateral externa, clássico logo Swoosh com jacquard Dior Oblique na cor marinho, bico arredondado com acabamento perfurado<br>\r\n\r\n- Logo no solado emborrachado, fecho em amarração com cadarço cinza/branco<br>\r\n\r\n- Lingua em tecido acolchoado na cor branca com padronagem Oblique na cor branca e etiqueta com logo Air Dior<br>\r\n\r\n- Acompanha dois saquinhos da marca, palmilhas extras com monograma Dior Oblique emborrachado na cor cinza, cadarço branco extra, dois pingentes sendo um com a silhueta Jordan e segundo Air Dior Wings, ambos com pequenos dust bags, duas formas de sapato para estruturação<br>', 17049.00, '0.00', 10, 'TênisNikeAirJordan1RetroHighDior1.jpg', '2021-10-23 18:17:22'),
(42, 'Nike', 'Air Jordan 1 low se Laser Blue', 'O Air Jordan 1 tem alta relevância no meio sneakerhead, e não é por menos, já que sua história revela a ousadia do maior jogador da NBA de todos os tempos.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Silhueta icônica desde a década de 80<br>\r\n\r\n- Perfurações estratégicas no cabedal para maior respirabilidade<br>\r\n\r\n- Colarinho acolchoado para um ajuste confortável<br>\r\n\r\n- Cabedal desenvolvido em couro<br>\r\n\r\n- Entressola com tecnologia de amortecimento Air<br>', 999.00, '0.00', 10, 'AirJordan1LowSeLaserBlue1.jpg', '2021-10-23 18:17:22'),
(43, 'Nike', 'Air Jordan 1 Low OG Chinese New Year', 'O Air Jordan 1 Low OG \'Ano Novo Chinês\' celebra o feriado lunar com bloqueio de cores clássico \'Bred\' e uma estampa jacquard festiva em todo o tecido superior.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Combinação de couro granulado com parte superior de Nobuck macio para durabilidade com sensação premium<br>\r\n\r\n- Parte frontal perfurada para ventilação<br>\r\n\r\n- Solado de borracha curvada, com a unidade Air-Sole no calcanhar para amortecimento e proteção contra impactos<br>\r\n\r\n- Solado de borracha sólida com profundas ranhuras flexíveis e padrão circular para fornecer tração e flexibilidade<br>', 1299.00, '0.00', 10, 'AirJordan1LowOgChineseNewYear1.jpg', '2021-10-23 18:17:22'),
(44, 'Nike', 'Tênis Nike Lebron XVIII NRG', 'O legado da lenda LeBron James vem ocupando posição de destaque dentro da cultura Sneaker e, através de cada lançamento, proporciona momentos inesquecíveis aos seus fãs.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Colorway inspirada nas vistas noturnas favoritas de LeBron<br>\r\n\r\n- Novo material superior – Knitposite 2.0 – adotou os conceitos do Flyknit e do Battleknit, adicionando estrutura e durabilidade, além de impedir que elas estiquem<br>\r\n\r\n- Colarinho acolchoado para um ajuste agradável<br>\r\n\r\n- Alça no colarinho auxilia a calçar o sneaker<br>\r\n\r\n- Cabedal desenvolvido em Kniposite 2.0<br>', 899.00, '0.00', 10, 'TênisNikeLebronXVIIINRG.png', '2021-10-23 18:17:22'),
(45, 'Nike', 'TÊNIS NIKE LEBRON XVIII LOW', 'Teremos Looney Tunes vs. Esquadrão Valentão no mais esperado filme de basquete do ano, Space Jam: Um Novo Legado. A Nike celebra o confronto histórico com um olhar divertido sobre o LeBron 18 Low.\r\n\r\nSobre o tênis:<br>\r\n\r\n- Collab Nike x Space Jam: A new galaxy<br>\r\n\r\n- Palmilhas personalizadas com a arte gráfica do “Papa-léguas” (direita), e “Coyote”(esquerda)<br>\r\n\r\n- Cabedal desenvolvido em material têxtil com sobreposições em material sintético<br>\r\n\r\n- Escritas “Beep Beep” e “Yeooooowwwwww........!” nas unidades visíveis Air Max<br>', 1099.00, '0.00', 10, 'NikeLebronXviiiLow1.jpg', '2021-10-23 18:17:22'),
(46, 'Nike', 'Tênis Nike LeBron 17 Monstars', 'O LeBron 17 aproveita a força e a velocidade do LeBron com contenção e sustentação para domínio na quadra.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- A cápsula de espuma macia diretamente por baixo da unidade de Max Air garante amortecimento no calcanhar<br>\r\n\r\n- O clipe estabilizador em plástico envolve o calcanhar para garantir segurança<br>\r\n\r\n- Entressola de espuma resistente\r\n\r\n- Sola de borracha durável<br>', 899.00, '0.00', 10, 'NikeLebron17Monstars1.jpg', '2021-10-23 18:17:22'),
(47, 'Nike', 'Air Jordan 1 mid Chicago', 'Esta versão retrô combina tons clássicos inspirados na história do tênis com color blocking renovado para criar uma nova versão de um design clássico.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Conforto e estilo<br>\r\n\r\n- Solado de borracha para mais durabilidade<br>\r\n\r\n- Cabedal em couro<br>\r\n\r\n- Perfurações para mais respirabilidade<br>\r\n\r\n- Entressola com unidade Air<br>', 899.00, '0.00', 10, 'AirJordan1MidChicago1.jpg', '2021-10-23 18:17:22'),
(48, 'Nike', 'TÊNIS NIKE AIR VAPORMAX EVO', 'Como uma das marcas esportivas mais respeitadas do mundo, a Nike constantemente olha para suas próprias raízes para inspirar suas coleções atuais. Deste modo, uma das silhuetas mais buscadas da marca no momento, nos apresenta mais uma variante desta linha, que combina as características distintivas de sete ícones da Nike, tornando-se assim um sinônimo de conforto e lifestyle.<br>\r\n\r\nSobre o tênis:<br>\r\n\r\n- Perfurações estratégias na parte superior para maior respirabilidade<br>\r\n\r\n- Escrita “I am my father’s legacy” na palmilha presta homenagem ao falecido pai do astro<br>\r\n\r\n- Cabedal desenvolvido em mescla de materiais<br>\r\n\r\n- Entressola com tecnologia de amortecimento Zoom Air<br>', 1399.00, '0.00', 10, 'TênisNikeAirVapormaxEvo.jpg', '2021-10-23 18:17:22'),
(49, 'New Balance', 'Tênis New Balance X-Racer', 'Sobre o tênis:<br>\r\n\r\n- Entressola ABZORB para maior amortecimento, absorção de impacto e conforto<br>\r\n\r\n- Cabedal em sintético<br>\r\n\r\n- Sola de borracha durável e com excelente tração<br>\r\n\r\n- ABZORB - O componente em borracha no ABZORB aumenta o amortecimento e as propriedade de resistência a compressão ajudando na absorção de altos impactos<br>', 699.00, '0.00', 10, 'TênisNewBalanceX-Racer1.jpg', '2021-10-23 18:17:22'),
(50, 'New Balance', 'Tênis New Balance 850 branco ', 'Sobre o tênis:<br>\r\n\r\n- Entressola ABZORB para maior conforto e amortecimento<br>\r\n\r\n- Cabedal em couro sintético e tecido<br>\r\n\r\n- Tecnologia Rollbar para suporte e estabilidade<br>\r\n\r\n- O tênis mantem o espírito independente que a marca carrega, removendo o famoso N das laterais, com sobreposições de materiais premium no cabedal e formas onduladas e coloridas<br>', 599.00, '0.00', 10, 'NewBalance850branco1.jpg', '2021-10-23 18:17:22'),
(51, 'New Balance', 'Tênis New Balance 237 Verde', 'Sobre o tênis:<br>\r\n\r\n- O cabedal foi elaborado com um incrível visual que mistura passado e presente<br>\r\n\r\n- Cabedal em couro sintético e tecidoOs destaques desse lançamento estão na lateral do calçado com um logotipo N superdimensionado e uma entressola em EVA com corte arrojado que remetem a modernidade<br>\r\n\r\n- A sola de borracha macia e o visual arrojado garante estilo para todas as horas<br>', 429.00, '0.00', 10, 'NewBalance237Verde1.jpg', '2021-10-23 18:17:22'),
(52, 'New Balance', 'Tênis New Balance 997H Preto Laranja', 'Sobre o tênis:<br>\r\n\r\n- O tênis New Balance 997H é uma versão atualizada do clássico cult 997 e que traz toda versatilidade que um sneaker pode oferecer<br>\r\n\r\n- A letra “H” faz referência a “HYPOTHESIS”, uma forma diferente de pensar no desenvolvimento deste tênis de como ele seria no futuro e na proposta do seu uso para que combine em todas as ocasiões<br>', 449.00, '0.00', 10, 'NewBalance997HPretoLaranja1.jpg', '2021-10-23 18:17:22'),
(53, 'New Balance', 'Tênis New Balance Kawhi OMN1S Kawhi 2 Way', 'Sobre o tênis:<br>\r\n\r\n- O OMN1S é feito de uma malha superior e possui um painel de couro ou camurça que envolve o tornozelo<br>\r\n\r\n- Ele também tem uma nova pulseira da marca Balance na parte dianteira do pé e tecnologia de amortecimento FuelCell na entressola<br>', 789.00, '0.00', 10, 'NewBalanceKawhiOMN1SKawhi2Way1.jpg', '2021-10-23 18:17:22'),
(54, 'New Balance', 'New Balance 992 Kith Kithmas Burgundy', 'Sobre o tênis:<br>\r\n\r\n- Cadarços tonais, a marca KITH na línguas, o nome de Fieg nos calcanhares, os tradicionais \"N\" nas laterais em cores diferentes destinadas a cada interação, midsole dupla com sistema ENCAP e ABZORB extra robusta, e sola de borracha<br>', 325.00, '0.00', 10, 'NewBalance992KithKithmasBurgun2.jpg', '2021-10-23 18:17:22'),
(55, 'New Balance', 'New Balance Vision Racer Jaden Smith', 'Sobre o tênis:<br>\r\n\r\n- Patch de logo na lingueta, modelagem de recortes, estampa posterior de logo, tira dupla na abertura, bico arredondado, fechamento frontal por amarração e solado de borracha<br>\r\n\r\n- Solado: Borracha 100%<br>\r\n\r\n- Exterior: Couro 100%, Neoprene 100%, Nylon 100%, Poliéster Reciclado 100%, Borracha 100%<br>\r\n\r\n- Forro: Poliamida 100%<br>', 2548.00, '0.00', 10, 'NewBalanceVisionRacerJadenSmith1.jpg', '2021-10-23 18:17:22'),
(56, 'New Balance', 'New Balance 997S Baited', 'Sobre o tênis:<br>\r\n\r\n- Os tênis são dominados por uma delicada camurça de pele de porco, com um esquema de cores que começa escuro na parte superior e traseira, mas fica mais claro na parte inferior da frente<br>\r\n\r\n- Vindo em nobuck preto elegante, \"New Balance\" é gravado na língua, enquanto os laços tonais cobrem o antepé<br>\r\n\r\n- A parte superior do balcão do calcanhar é revestida de azul, seguido de amarelo e azul claro por baixo. Movendo-se para o corpo principal, uma seção do quarto superior aparece em um rico matiz roxo, próximo a paredes laterais em rosa escuro com um logotipo “N” contrastante costurado<br>\r\n\r\n- A parte mais brilhante do sapato é a caixa do pé frontal, que vem em uma paleta de cores ousadas em amarelo, complementada por uma fina tira laranja que aparece logo abaixo dos cadarços<br>', 199.00, '0.00', 10, 'NewBalance997SBaited1.jpg', '2021-10-23 18:17:22'),
(57, 'New Balance', 'New Balance 827 Abzorb Aime Leon', 'Sobre o tênis:<br>\r\n\r\n- Lançado como parte de uma coleção cápsula com a marca streetwear de NYC, o Aimé Leon Dore x 827 \'White\' usa um corredor New Balance retro lançado originalmente em 1999<br>\r\n\r\n- A parte superior apresenta uma base de malha branca com sobreposições de camurça sintética tonal, teia de tom e laços de renda multicoloridos<br>\r\n\r\n- Os sucessos da marca incluem um logotipo do lado ‘N’ e letras ‘ALD’ no calcanhar. A entressola ABZORB da New Balance oferece um passeio amortecido, completo com uma teia de TPU para estabilidade do meio do pé<br>', 699.00, '0.00', 10, 'NewBalance827AbzorbAimeLeon1.jpg', '2021-10-23 18:17:22'),
(58, 'New Balance', 'New Balance 801 Gore-tex the Apartment Toucan', 'Sobre o tênis:<br>\r\n\r\n- O 801 retro trail-running é um favorito cult no Japão e fica em casa nas prateleiras do apartamento. Eles escolheram cores que são sinônimos de equipamentos para atividades ao ar livre, que também adornam o tucano que vive na floresta<br>\r\n\r\n- Inesperadamente, esses sapatos seriam confortáveis ​​para atravessar a Amazônia, graças a um couro resistente e parte superior ripstop, forro GORE-TEX e hardware de metal hardcore<br>', 1255.00, '0.00', 10, 'NewBalance801Gore-textheApartmentToucan1.jpg', '2021-10-23 18:17:22'),
(59, 'New Balance', 'New Balance 57/40 Concepts Headin', 'Sobre o tênis:<br>\r\n\r\n- Tons de laranja pálido encontram contrapartes mais brilhantes e mais fortes adjacentes, enquanto tons neutros de creme e branco preenchem os espaços em branco ao longo da base e entressola, respectivamente<br>\r\n\r\n- Além do mais, os logotipos de cera “N” ajudam na conexão com o esporte, lembrando os fãs de longa data de abrir um pacote de cards de beisebol<br>', 187.00, '0.00', 10, 'NewBalance57_40ConceptsHeadin1.jpg', '2021-10-23 18:17:22'),
(60, 'New Balance', 'New Balance Test Run 3.0 Salehe Bembury', 'Sobre o tênis:<br>\r\n\r\n- Camurça cinza e couro branco se unindo na ponta do pé, já que os painéis azul claro e verde oferecem cor adicional no calcanhar<br>\r\n\r\n- A tira zip-zag, um detalhe característico do Test Run Project 3.0, aparece em branco com a marca New Balance cinza, e o nome de Bembury é então apresentado em neon na etiqueta de língua laranja vizinha<br>\r\n\r\n- Por último, o tênis é finalizado com uma sola intermédia Fresh Foam estampada em branco e dourado e uma sola Vibram amarela<br>', 2700.00, '0.00', 10, 'NewBalanceTestRun3.0SaleheBembury1.jpg', '2021-10-23 18:17:22'),
(61, 'New Balance', 'New Balance 996 Franck Muller Gold', 'Sobre o tênis:<br>\r\n\r\n- Este colab apresenta duas cores metálicas do 996 inspiradas em símbolos clássicos da relojoaria<br>\r\n\r\n- Um apresenta bastante prata, referenciando os acabamentos metálicos brilhantes do relógio de aço inoxidável Iron Croco por Muller, que é contrastado por couro marinho em relevo com textura de pele de crocodilo faux, muito parecido com uma pulseira de relógio exótica<br>\r\n\r\n- Enquanto a opção Gold Croco atinge o equilíbrio perfeito entre glamour e berrante por não ter muito do dourado no topo, e novamente a marinha ajuda a suavizar as coisas levemente<br>\r\n\r\n- Numerais cursivos de grandes dimensões gravados em seções de couro metálico da parte superior e impressão de palmilha multicolorida para combinar<br>', 269.00, '0.00', 10, 'NewBalance996FranckMullerGold1.jpg', '2021-10-23 18:17:22'),
(62, 'New Balance', 'Solebox x New Balance 1500 “Toothpaste” Pack', 'Sobre o tênis:<br>\r\n\r\n- O M1500Bor \'Solebox\' apresenta uma parte superior de malha aberta branca projetada para respirabilidade aprimorada<br>\r\n\r\n- Apresenta detalhes em camurça laranja, sobreposições de couro branco, uma lingueta e gola acolchoadas para um ajuste confortável, um fechamento com cordões para travar e uma sola intermédia acolchoada para maior suporteo<br>', 648.00, '0.00', 10, 'SoleboxxNewBalance1500ToothpastePack1.jpg', '2021-10-23 18:17:22'),
(63, 'New Balance', 'Provider x New Balance 1500', 'Sobre o tênis:<br>\r\n\r\n- O esquema de cores escolhido contém Azul, Preto e Carvão com uma biqueira perfurada e a parte superior contém Suede<br>', 1500.00, '0.00', 10, 'ProviderxNewBalance15001.jpg', '2021-10-23 18:17:22'),
(64, 'New Balance', 'New Balance MT580 Packer Shoes Pine', 'Sobre o tênis:<br>\r\n\r\n- O tênis resultante combina tons de vermelho escuro em camurças premium e malha balística, enquanto um gráfico de floresta de pinheiros decora tanto o rótulo da língua quanto o forro<br>\r\n\r\n- Os toques adicionais incluem alguns pops vibrantes da 3M, bem como traços de roxo na entressola e atacadore<br>', 300.00, '0.00', 10, 'NewBalanceMT580PackerShoesPine1.jpg', '2021-10-23 18:17:22'),
(65, 'New Balance', 'New Balance 2002R Salehe Bembury Peace', 'Sobre o tênis:<br>\r\n\r\n- Apresenta um couro laranja e camurça superior inspirado pelas cores distintivas do Antelope Canyon<br>\r\n\r\n- As inserções de malha estão também incluídas para umconfortoóptimo . O icónico\"N\" da marca é exibido num forro azul<br>\r\n\r\n- E para melhorar o design, Salehe Bembury optou por uma entressola branca com pequenas manchas cor-de-laranja<br>', 4789.00, '0.00', 10, 'NewBalance2002RSaleheBemburyPeace1.jpg', '2021-10-23 18:17:22'),
(66, 'New Balance', 'J.Crew x New Balance 998 “Concrete Jungle”', 'Sobre o tênis:<br>\r\n\r\n- O tênis, fabricado nos Estados Unidos, foi batizado CONCRETE JUNGLE e traz uma colorway que mistura verdes, laranja, marrom e cinza em materiais como nobuck e suede de primeiríssima qualidade<br>', 2000.00, '0.00', 10, 'J.CrewxNewBalance998ConcreteJungle1.jpg', '2021-10-23 18:17:22'),
(67, 'New Balance', 'New Balance R770 SNS', 'Sobre o tênis:<br>\r\n\r\n- Mix de estampas<br>', 139.00, '0.00', 10, 'NewBalanceR770SNS1.jpg', '2021-10-23 18:17:22'),
(68, 'New Balance', 'New Balance 992 YCMC Rewind', 'Sobre o tênis:<br>\r\n\r\n- Chegando bem a tempo para o verão, a colaboração ilumina o clássico por meio de estampas retrô e coloridas<br>\r\n\r\n- Embora a base possa ser atenuada com o uso de camurça azul-marinho profunda, a energia rapidamente se intensifica à medida que tons de roxo brilhante e ciano se complementam ao longo da gola e do dedo do pé. Além do mais, para dar vida ao logo “N” e à marca, a marca optou por um toque de realce verde<br>\r\n\r\n- Finalmente, em um aceno mais aberto à época, os atacadores possuem uma variedade de quatro partes, incluindo preto, branco e duas opções padronizadas<br>', 185.00, '0.00', 10, 'NewBalance992YCMCRewind1.jpg', '2021-10-23 18:17:22'),
(69, 'New Balance', 'New Balance 992 Nice Kicks Amoeba Music', 'Sobre o tênis:<br>\r\n\r\n- Ambas as interações do New Balance 992 possuem uma paleta de cores inspirada nas placas de néon das lojas de discos da Amoeba<br>\r\n\r\n- Eles são construídos misturando malha e camurça, e são realçados por cadarços nas cores \"Teal\" e \"Red\", além de uma midsole ABZORB e sola de borracha preta<br>', 1349.00, '0.00', 10, 'NewBalance992NiceKicksAmoebaMusic1.jpg', '2021-10-23 18:17:22'),
(70, 'New Balance', 'New Balance 550 Branco Multicolor', 'Sobre o tênis:<br>\r\n\r\n- O tênis combina as cores amarelo, veremlho, azul marinho, verde, cinza e branco.<br>', 159.00, '0.00', 10, 'NewBalance550BrancoMulticolor1.jpg', '2021-10-23 18:17:22'),
(71, 'New Balance', 'Luzes noturnas New Balance 801 Herschel', 'Sobre o tênis:<br>\r\n\r\n- Preto e laranja<br>\r\n\r\n- Entressola ABZORB para maior conforto e amortecimento<br>\r\n\r\n- Cabedal em couro sintético e tecido<br>\r\n\r\n- Tecnologia Rollbar para suporte e estabilidade<br>', 1239.00, '0.00', 10, 'LuzesNoturnasNewBalance801Herschel1.jpg', '2021-10-23 18:17:22'),
(72, 'New Balance', 'New Balance 999 Concepts Hyannis', 'Sobre o tênis:<br>\r\n\r\n- O estilo de inspiração náutica é feito em camurça de pele de porco e o foxing em nobuck em relevo premium para um lindo e bem trabalhado sapato MiUSA<br>\r\n\r\n- Bandeiras náuticas são visíveis na palmilha e na lingueta, com uma bandeira maior da Concepts costurada na palmilha<br>\r\n\r\n- The Concepts x New Balance MADE US 999 foi fabricado em Skowhegan, Maine, uma das cinco instalações de manufatura da New Balance na Nova Inglaterra<br>', 810.00, '0.00', 10, 'NewBalance999ConceptsHyannis1.jpg', '2021-10-23 18:17:22'),
(73, 'Converse', 'Converse Chuck Taylor All Star Off-White ', 'Sobre o tênis:<br>\r\n\r\n- Embora a tela toda branca do Converse Chuck Taylor All-Star 70 Hi Off-White traça semelhanças com as cores clássicas não colaborativas, há muitos pontos de diferenciação<br>\r\n\r\n- Para começar, a entressola com temática de fita isolante em preto e branco acena com um dos principais motivos de design do Off-White<br>\r\n\r\n- A seguir, “Off-White ™ para CONVERSE‘ CHUCK TAYLOR ALL-STAR ’Malden, Massachusetts, EUA c. 1917” é a tela impressa no painel medial interno da gáspea. Para completar este Chuck Taylor Off-White, um patch de estrela modificada aparece no tornozelo e uma gravata de zíper laranja exclusiva é enganchada nos atacadores<br>', 3750.00, '0.00', 10, 'ConverseChuckTaylorAll-Star70sHiOff-White1.jpg', '2021-10-23 18:17:22'),
(74, 'Converse', 'Converse Chuck Taylor All-Star Hi Space Jam', 'Sobre o tênis:<br>\r\n\r\n- O Chuck Taylor All-Star Space Jam apresenta um chip de computador similar com um padrão superior como o AF1 Space Jam Computer Chip, só que desta vez com uma variedade de personagens Looney Tunes impressos no topo<br>\r\n\r\n- Uma clássica sola branca e preta com uma biqueira combinando completam o design<br>\r\n\r\n- Cor: BLACK/MULTI/WHITE<br>', 1850.00, '0.00', 10, 'ConverseChuckTaylorAll-StarHiSpaceJam1.jpg', '2021-10-23 18:17:22'),
(75, 'Converse', 'Tênis Converse Run Star Motion High Light Twine ', 'Sobre o tênis:<br>\r\n\r\n- Reimaginada de dentro para fora, a postura elevada e a entressola de espuma CX ajudam a trazer conforto de nível superior a cada passada<br>\r\n\r\n- A parte superior permanece fiel ao original, complementada por detalhes de design voltados para o futuro para uma expressão ousada<br>\r\n\r\n- Uma plataforma ondulada exagerada e alças de suporte elevam você e o mantêm estável com tração excepcional<br>\r\n\r\n- Parte superior em lona 100% orgânica<br>\r\n\r\n- Sola de borracha e detalhes de Chuck 70 premium<br>\r\n\r\n- Riscas esculpidas onduladas<br>\r\n\r\n- A palmilha de espuma CX e a entressola leve absorvem o impacto e dão suporte para todo o dia<br>\r\n\r\n- Biqueira icônica e calcanhar em borracha para uma tração excepcional<br>', 699.00, '0.00', 10, 'ConverseRunStarMotionHighLightTwine1.jpg', '2021-10-23 18:17:22'),
(76, 'Converse', 'Converse Run Star Hike Natasha Cloud', 'Sobre o tênis:<br>\r\n\r\n- Os gráficos das pétalas são colocados nos painéis laterais e no topo da garganta através de contornos brancos contra um fundo “Quartzo rosa”, sendo o primeiro criado com um sombreado ligeiramente mais escuro<br>\r\n\r\n- Línguas, atacadores e biqueiras de borracha também são encharcados no tom rosado, deixando as únicas outras notas contrastantes visíveis através dos ilhós prateados metálicos<br>\r\n\r\n- Entressolas grossas e trações dentadas prontas para caminhadas seguem o exemplo com mais peles de “quartzo rosa” para finalizar sua apresentação de design<br>', 606.00, '0.00', 10, 'ConverseRunStarHikeNatashaCloud1.jpg', '2021-10-23 18:17:22'),
(77, 'Converse', 'Tênis cano alto x Space Jam Run Star Motion', 'Sobre o tênis:<br>\r\n\r\n- Patch de logo na lingueta, bico arredondado, fechamento frontal por amarração, logo na palmilha e solado chunky de borracha<br>\r\n\r\n- Forro: Tecido 100%<br>\r\n\r\n- Solado:Borracha 100%<br>\r\n\r\n- Exterior: Tecido 100%<br>', 1512.00, '0.00', 10, 'ConversexSpaceJamANewLegacyRunStarMotion1.jpg', '2021-10-23 18:17:22'),
(78, 'Converse', 'Converse Gianno Golf Le Fleur Lavender ', 'Sobre o tênis:<br>\r\n\r\n- Feito em colaboração com Tyler, o Criador, o Golf Le Fleur x Converse Gianno Low ‘Lavender’ apresenta um formato largo e volumoso em linha com a estética predominante dos anos 90 do tênis<br>\r\n\r\n- A construção em camurça em camadas em um acabamento pastel suave é utilizada em toda a parte superior, acentuada com detalhes reflexivos e apoiada por uma entressola em EVA marfim e sola de borracha reforçada<br>\r\n\r\n- Os sucessos da marca floral do Golf Le Fleur adornam a língua e o calcanhar lateral<br>', 692.00, '0.00', 10, 'ConverseGiannoGolfLeFleurLavender1.jpg', '2021-10-23 18:17:22'),
(79, 'Converse', 'Converse CPX70 Zebra (W)', 'Sobre o tênis:<br>\r\n\r\n- Os ilhoses são prateados e brilhosos, incluindo os dois laterais, que servem para facilitar a transpiração adequada os pés<br>\r\n\r\n- A palmilha proporciona um conforto adicional e, junto com a sola, que mescla designs de todos os solados<br>\r\n\r\n- Tecido resistente 100% algodão<br>\r\n\r\n- Ilhoses em metal<br>\r\n\r\n- Biqueira em borracha reforçado<br>\r\n\r\n- Solado de borracha<br>\r\n\r\n- Design único do solado com parte do ERX,70s e pro leather<br>', 1246.00, '0.00', 10, 'ConverseCPX70Zebra_W_1.jpg', '2021-10-23 18:17:22'),
(80, 'Converse', 'Converse Chuck Taylor All-Star 70s Hi Hello ', 'Sobre o tênis:<br>\r\n\r\n- Na parte interna dos canos o Patch Logo com o logo comemorativo do Converse All Star Chuck Taylor 70 é aplicado em couro<br>\r\n\r\n- As palmilhas com tecnologia Ortholite para amortecimento e conforto o dia todo. A vira de borracha envernizada feita em uma forma americana, mais justa aos pés ganha a Heel Logo em preta com a assinatura Converse All Star Chuck Taylor e o solado vulcanizado garante a aderência adequada ao caminhar<br>\r\n\r\n- Midsole vintage<br>\r\n\r\n- Amortecimento Ortholite<br>\r\n\r\n- Sola / Entressola: Borracha Vulcanizada<br>', 496.00, '0.00', 10, 'ConverseChuckTaylorAll-Star70sHiHello1.jpg', '2021-10-23 18:17:22'),
(81, 'Converse', 'Converse Chuck Taylor All-Star 70 Hi Keith', 'Sobre o tênis:<br>\r\n\r\n- Collab Converse x Keith Haring<br>\r\n\r\n- Dois ilhoses laterais para maior respirabilidade<br>\r\n\r\n- Palmilhas OrthoLite para maior conforto<br>\r\n\r\n- Cabedal desenvolvido em lona<br>\r\n\r\n- Entressola em espuma<br>\r\n\r\n- Solado de borracha<br>', 699.00, '0.00', 10, 'ConverseChuckTaylorAll-Star70HiKeith1.jpg', '2021-10-23 18:17:22'),
(82, 'Converse', 'Converse Chuck 70 Utility \"Steel / Egret\"', 'Sobre o tênis:<br>\r\n\r\n- As gáspeas são revestidas com lona azul aço com a adição de uma gaiola translúcida que corre ao longo das laterais sobre os olhos e o remendo de tornozelo All Starx<br>\r\n\r\n- Uma sobreposição de borracha ondulada fica acima da entressola branca clássica, que apresenta duas linhas sólidas de realce preto e um banner de pára-choque<br>\r\n\r\n- Os detalhes adicionais incluem atacadores arredondados, ilhós metálicos e transparentes contrastantes e amortecimento OrthoLite para maior conforto<br>', 773.00, '0.00', 10, 'ConverseChuck70UtilitySteelEgret1.jpg', '2021-10-23 18:17:22'),
(83, 'Converse', 'Converse Weapon CX', 'Sobre o tênis:<br>\r\n\r\n- Apresenta a barra Y original para estabilidade, uma língua de tamanho grande e nova espuma CX - uma palmilha confortável e leve dentro de uma sola redesenhada para suportar seus passos e movimentos<br>\r\n\r\n- Cano médio em couro macio premium<br>\r\n\r\n- Barra em Y na lateral para suporte de tornozelo<br>\r\n\r\n- Gola de espuma para amortecimento acolchoado<br>\r\n\r\n- Palmilha de espuma CX e entressola leve para ajudar a absorver o impacto<br>\r\n\r\n- Proporção totalmente remodelada<br>', 629.00, '0.00', 10, 'ConverseWeaponCX1.jpg', '2021-10-23 18:17:22'),
(84, 'Converse', 'Converse Chuck 70 Hi \"Sunflower Trek\"', 'Sobre o tênis:<br>\r\n\r\n- Entressola está uma nova sola de trekking, coberta por um design de mármore multicolorido com toques de cinza-azulado, branco, vermelho, amarelo e preto<br>\r\n\r\n- O acabamento em mármore dá uma aparência camuflada, mas quando você vira o calçado sobre o perfil da sola, você pode ver que é muito mais um acabamento artístico, parecendo como se você tivesse entrado na pintura<br>', 922.00, '0.00', 10, 'ConversesChuck70HiSunflowerTrek1.jpg', '2021-10-23 18:17:22'),
(85, 'Converse', 'Converse Run Star Hike Hi Archive Print ', 'Sobre o tênis:<br>\r\n\r\n- Patch Logo do tradicional Converse Chuck Taylor All Star é aplicado na parte interna dos canos, em borracha alto relevo off white<br>\r\n\r\n- Os dois ilhoses laterais permitem uma transpiração adequada aos pés. Possui palmilhas SmartFOAM para melhor amortecimento<br>\r\n\r\n- O solado plataforma tratorado, com aproximadamente 5,5 cm de altura (podendo variar conforme o tamanho do tênis), é feito em EVA e borracha, dando mais resistência ao tênis e recebendo a icônica estrela da marca<br>', 649.00, '0.00', 10, 'ConverseRunStarHikeHiArchivePrint1.jpg', '2021-10-23 18:17:22'),
(86, 'Converse', 'Converse GLF Gianno Ox Meerkat', 'Sobre o tênis:<br>\r\n\r\n- Esta edição hospeda painéis de couro Meerkat contrastados por uma paleta multicolorida expressa nos detalhes de malha, redes e inserções têxteis pontilhadas<br>\r\n\r\n- Cadarços brilhantes com laços reflexivos e uma aba ondulada adicionam capricho à estética da trilha<br>\r\n\r\n- Uma entressola em EVA verde e uma sola de borracha robusta são adicionadas sob os pés<br>', 828.00, '0.00', 10, 'ConverseGLFGiannoOxMeerkat1.jpg', '2021-10-23 18:17:22'),
(87, 'Converse', 'Converse Chuck Taylor All-Star Renew Low Mason Taupe ', 'Sobre o tênis:<br>\r\n\r\n- Versão Renew tem cabedal de lona com biqueira e sola intermédia de borracha. Comparando a impressão \"A vida é curta demais para desperdiçar\"<br>\r\n\r\n- Cor: Mason Taupe/Black/White<br>', 404.00, '0.00', 10, 'ConverseChuckTaylorAll-StarRenewLowMasonTaupe1.jpg', '2021-10-23 18:17:22'),
(88, 'Converse', 'Converse Gianno Golf Le Fleur Skylight', 'Sobre o tênis:<br>\r\n\r\n- Amortecimento, antiderrapante, vestível<br>\r\n\r\n- Superior Corte baixo<br>\r\n\r\n- Salto plano<br>\r\n\r\n- Cor: Azul e amarelo<br>', 704.00, '0.00', 10, 'ConverseGiannoGolfLeFleurSkylight1.jpeg', '2021-10-23 18:17:22'),
(89, 'Converse', 'TÊNIS CONVERSE CHUCK TAYLOR ALL STAR CX ', 'Sobre o tênis:<br>\r\n\r\n- O Tênis Converse Chuck Taylor All Star, é uma reconstrução inspirada no último modelo para performance, lançado pela marca nos anos 70<br>\r\n\r\n- Dois ilhoses laterais para maior respirabilidade<br>\r\n\r\n- Silhueta clássica<br>\r\n\r\n- Cabedal leve e respirável<br>\r\n\r\n- Cabedal confeccionado em lona<br>\r\n\r\n- Entressola em espuma CX<br>\r\n\r\n- Solado de borracha<br>', 429.00, '0.00', 10, 'ConverseChuckTaylorAllStarCx1.jpg', '2021-10-23 18:17:22'),
(90, 'Converse', 'Brain Deads Converse Chuck 70 and Bosey Ox Deliver Head-Turning Deconstruction', 'Sobre o tênis:<br>\r\n\r\n- Ostentando uma parte superior de lona preta ao lado de uma entressola em tons de garça e preto. Tal como acontece com todos os melhores Chuck 70s, o tênis é acabado com costura branca contrastante, um conjunto de atacadores brancos e uma placa de licença preta clássica - no entanto, é dividido para manter o tema de Brain Dead<br>\r\n\r\n- Completando o par DSM está a marca Brain Dead e Converse nos painéis intermediários, e o par de palmilhas de marca<br>', 858.00, '0.00', 10, 'BrainDeadsConverseChuck70andBoseyOxDeliverHead-TurningDeconstruction1.jpg', '2021-10-23 18:17:22'),
(91, 'Converse', 'DRKSHDW x Converse TURBODRK Chuck 70 ', 'Sobre o tênis:<br>\r\n\r\n- Forro: Tecido 100%<br>\r\n\r\n- Solado:Borracha 100%<br>\r\n\r\n- Exterior: Tecido 100%<br>\r\n\r\n- Com biqueira tripla, sola dupla, lingueta estendida e biqueira quadrada<br>', 960.00, '0.00', 10, 'DRKSHDWxConverseTURBODRKChuck701.jpg', '2021-10-23 18:17:22');
INSERT INTO `produtos` (`id`, `marca`, `name`, `desc`, `price`, `rrp`, `quantity`, `img`, `date_added`) VALUES
(92, 'Converse', 'Chuck 70 “Holiday Sweater” pack', 'Sobre o tênis:<br>\r\n\r\n- Uma impressão de fair isle adorna a parte superior, com a primeira exibindo uma paleta de cores festiva de verde e vermelho<br>\r\n\r\n- O mesmo tema é visto no emblema da assinatura de Converse no tornozelo, enquanto a aba do calcanhar é vestida com o mesmo padrão<br>\r\n\r\n- A iteração em preto e branco apresenta detalhes mais atenuados, com flocos de neve brancos sobre um fundo preto<br>\r\n\r\n- Ambos os designs são arredondados com entressolas e biqueira off-white, mantendo-se fiéis ao visual clássico do Chuck 70<br>', 191.00, '0.00', 10, 'Chuck70HolidaySweaterPack1.jpg', '2021-10-23 18:17:22'),
(93, 'Converse', 'Converse ERX 260 Mid Just Don Metal', 'Sobre o tênis:<br>\r\n\r\n- Antiderrapante, vestível<br>\r\n\r\n- Material de Solado Linguado de borracha<br>\r\n\r\n- Superior Corte alto<br>\r\n\r\n- Salto plano<br>\r\n\r\n- Branco preto<br>', 400.00, '0.00', 10, 'ConverseERX260MidJustDonMetal1.jpg', '2021-10-23 18:17:22'),
(94, 'Converse', 'Converse Basketball Holiday 2020', 'Sobre o tênis:<br>\r\n\r\n- Do ponto de vista do desempenho, o All Star BB Evo oferece um design baixo e elegante com uma malha fundida superior e uma entressola de espuma React rebatível. Ele foi projetado para jogadores que jogam na ponta dos pés, como Shai Gilgeous-Alexander e Kelly Oubre Jr.<br>\r\n\r\n- As iterações de corte alto e baixo do G4 oferecem um ajuste mais resistente e de suporte para goleadores como Draymond Green, mas sua mistura de Zoom Air e espuma React certifique-se de que ainda está leve e confortável<br>\r\n\r\n- Finalmente, o Pro Leather fornece uma construção de couro flexível para o estilo fora da quadra, embora já tenha se elevado acima da madeira dura nos pés de Julius “Dr. J” Erving<br>', 661.00, '0.00', 10, 'ConverseBasketballHoliday20201.jpg', '2021-10-23 18:17:22'),
(95, 'Converse', 'CONVERSE AERO JAM MID HORNETS HOME', 'Sobre os tênis:<br>\r\nCores: branco,preto, roxo, amarelo e verde água.<br>', 2205.00, '0.00', 10, 'ConverseAeroJamMidHornetsHome1.jpg', '2021-10-23 18:17:22'),
(96, 'Converse', 'CONVERSE CHUCK TAYLOR ALL-STAR 70S OX COMME DES GARCONS PLAY MULTI-HEART WHITE', 'Sobre o tênis:<br>\r\n\r\n- Data de lançamento 12 de junho de 2020<br>\r\n\r\n- Cor BRANCO / VERMELHO<br>\r\n\r\n- Material de Solado: Linguado de borracha<br>\r\n\r\n- Superior: Corte baixo<br>', 882.00, '0.00', 10, 'ConverseChuckTaylorAll-Star70sOxCommeDesGarconsPlayMulti-HeartWhite2.jpg', '2021-10-23 18:17:22'),
(97, 'Converse', 'YEEZY BOOST 350 V2 \"ZEBRA\"', 'Tênis Yeezy Boost 350 V2 \"Zebra\"<br>\r\n-Cor: branco<br>\r\n-Material: algodão<br>\r\n-Com fechamento por cadarço na frente<br>\r\n-Solado com logo e solado em borracha<br>', 1550.00, '0.00', 20, 'img1.jpg', '2021-11-08 18:52:37'),
(98, 'Nike', 'LEBRON SOLDIER 12 XII PRETO VERMELHO', 'Sobre o tênis: <br>\r\nCabedal em knit trabalhado circular proporciona suporte respirável<br>\r\nTiras dinâmicas se cruzam no mediopé e no tornozelo para prender você<br>\r\nEntressola de espuma com unidade Nike Zoom Air para amortecimento com ótima resposta<br>\r\nPadrão de borracha durável proporciona excelente tração<br>', 500.00, '0.00', 20, 'img3.jpg', '2021-11-08 19:00:55'),
(99, 'Nike', 'Tênis Nike Kyrie 5 SpongeBob SquarePants Pineapple House', 'Sobre o tênis: <br>\r\nCabedal coberto pela estampa da casa de abacaxi do Bob Esponja<br>\r\nToques divertidos como as folhas do abacaxi usadas nos passadores dão um destaque extra<br>', 1500.00, '0.00', 20, 'img6.jpg', '2021-11-08 19:08:51');

--
-- Índices de tabelas apagadas
--

--
-- Índices de tabela `cadastro`
--
ALTER TABLE `cadastro`
  ADD PRIMARY KEY (`id`);

--
-- Índices de tabela `produtos`
--
ALTER TABLE `produtos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de tabelas apagadas
--

--
-- AUTO_INCREMENT de tabela `cadastro`
--
ALTER TABLE `cadastro`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;

--
-- AUTO_INCREMENT de tabela `produtos`
--
ALTER TABLE `produtos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=100;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
